<a href="https://colab.research.google.com/github/Yogita6693/Numpy_Pandas/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
p = (3, 0, 1, 5, 7, 2)
try:
   p[6] = 9
except:
   print("Error occured")
finally:
  print("After error occured")

Error occured
After error occured


In [ ]:
def evenN(number):
  if number%2==0:
    return number

arr=range(50)
even=list(filter(evenN,arr))
print(even)


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


In [2]:
list = [1,2,3,4,5,6]
print(list)
tuple = tuple(list)
tuple


[1, 2, 3, 4, 5, 6]


(1, 2, 3, 4, 5, 6)

In [9]:
import numpy as np
list = [1,2,3,4,5,6]
arr = np.array(list)
print(arr)
print(arr.ndim)
arr.shape

[1 2 3 4 5 6]
1


(6,)

In [13]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [15]:
ar = arr+2
ar

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [20]:
np.zeros([4,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
print(np.linspace(0,10,11))
np.linspace(0,5,10)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.rand(5)

array([0.80307363, 0.60388685, 0.08495364, 0.32976059, 0.83291336])

In [37]:
np.random.randn()

array([[-0.34850872, -0.25537721],
       [-0.32582554, -0.15464759]])

In [42]:
rand = np.random.rand(16)
print(rand)
rand.reshape(1,16)
rand.reshape(4,4)
rand.reshape(2,2,2,2)

[0.09229671 0.35619251 0.10672569 0.99149059 0.21074919 0.4405147
 0.61848987 0.06248399 0.03834969 0.0190499  0.97561004 0.83281369
 0.9061612  0.31392125 0.24921206 0.99210863]


array([[[[0.09229671, 0.35619251],
         [0.10672569, 0.99149059]],

        [[0.21074919, 0.4405147 ],
         [0.61848987, 0.06248399]]],


       [[[0.03834969, 0.0190499 ],
         [0.97561004, 0.83281369]],

        [[0.9061612 , 0.31392125],
         [0.24921206, 0.99210863]]]])

In [44]:
arr = np.arange(2,7)
arr

array([2, 3, 4, 5, 6])

In [47]:
arr>2

array([False,  True,  True,  True,  True])

In [49]:
arr[[False,  True,  True,  True,  True]]

array([3, 4, 5, 6])

In [54]:
arrr = np.arange(2,10)
arrr[arrr>2]

array([3, 4, 5, 6, 7, 8, 9])

In [58]:
arr = np.arange(1,12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
arr[0] = 2
arr[4] = 2
arr[8] = 2
arr

array([ 2,  2,  3,  4,  2,  6,  7,  8,  2, 10, 11])

In [60]:
arr.min()

2

In [61]:
len(arr)

11

In [65]:
arr[: :-1]

array([11, 10,  2,  8,  7,  6,  2,  4,  3,  2,  2])

In [66]:
arr[: :-1].argmin()

2

In [71]:
len(arr)-arr[: :-1].argmin()

9

In [74]:
np.where(arr == arr.min())

(array([0, 1, 4, 8]),)

In [76]:
np.where(arr == arr.min())[0]

array([0, 1, 4, 8])

In [77]:
np.where(arr == arr.min())[0][-1]

8

In [78]:
print(arr)
print(arr.max())
print(np.argmax(arr))

[ 2  2  3  4  2  6  7  8  2 10 11]
11
10


In [84]:
arr = np.arange(1,17)
print(arr)
arr_2d = arr.reshape(4,4)
print(arr_2d)
arr_1d = arr_2d.flatten()
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [86]:
print(arr_2d)
arr_2d.transpose()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [89]:
arr1 = np.random.rand(2,4)
arr2 = np.random.rand(2,4)
print(arr1)
print("-----------")
print(arr2)

[[0.25014044 0.96103718 0.93944872 0.4455129 ]
 [0.62652699 0.82727707 0.5825983  0.55727089]]
-----------
[[0.42014287 0.52069136 0.31552449 0.57794073]
 [0.7201526  0.75112906 0.35645699 0.12847401]]


In [90]:
np.concatenate((arr1,arr2),axis=0)

array([[0.25014044, 0.96103718, 0.93944872, 0.4455129 ],
       [0.62652699, 0.82727707, 0.5825983 , 0.55727089],
       [0.42014287, 0.52069136, 0.31552449, 0.57794073],
       [0.7201526 , 0.75112906, 0.35645699, 0.12847401]])

In [91]:
np.concatenate((arr1,arr2),axis=1)

array([[0.25014044, 0.96103718, 0.93944872, 0.4455129 , 0.42014287,
        0.52069136, 0.31552449, 0.57794073],
       [0.62652699, 0.82727707, 0.5825983 , 0.55727089, 0.7201526 ,
        0.75112906, 0.35645699, 0.12847401]])

In [92]:
arr3 = np.random.rand(4,4)
arr3

array([[0.78892104, 0.18228571, 0.63515118, 0.43581621],
       [0.74590584, 0.18270161, 0.40925055, 0.05378985],
       [0.78542521, 0.88303831, 0.45854975, 0.76362973],
       [0.07920304, 0.59722106, 0.72888743, 0.88647744]])

In [94]:
np.hsplit(arr3,2)

[array([[0.78892104, 0.18228571],
        [0.74590584, 0.18270161],
        [0.78542521, 0.88303831],
        [0.07920304, 0.59722106]]), array([[0.63515118, 0.43581621],
        [0.40925055, 0.05378985],
        [0.45854975, 0.76362973],
        [0.72888743, 0.88647744]])]

In [95]:
np.vsplit(arr3,2)

[array([[0.78892104, 0.18228571, 0.63515118, 0.43581621],
        [0.74590584, 0.18270161, 0.40925055, 0.05378985]]),
 array([[0.78542521, 0.88303831, 0.45854975, 0.76362973],
        [0.07920304, 0.59722106, 0.72888743, 0.88647744]])]